### ISSUE TITLE
[Hands-on Labs > Explore DynamoDB with the CLI > Deleting Data] Wrong description of delete operation.

### ISSUE THREAD

**Issue by maciok** [aws-samples/amazon-dynamodb-labs#58]
Probably because of copy-paste mistake the description for delete operation states that it creates or replace item:

> The DynamoDB DeleteItem API is used to **_create a new item or to replace existing items completely with a new item_**. It is invoked using the delete-item CLI command.

**Comment by switch180** [comment]
It's fixed in ed56f94c 

Resolving
