### ISSUE TITLE
Should CLI and Python versions be updated?

### ISSUE THREAD

**Issue by NoSQLKnowHow** [aws-samples/amazon-dynamodb-labs#60]
on pages like [this one](http://localhost:1313/design-patterns/setup/step2.html) it mentions AWS CLI 1.x, but we really should be using 2.x.

Also, should we switch Python version as well? For python, we should likely be on a newer version as well. This mentions 3.6.x when Python is already up to 3.9.

**Comment by switch180** [comment]
CLI and Python versions now up to date. New doc page mentions the latest version
