### ISSUE TITLE
Recommend Targeting a New Tab for Console Links

### ISSUE THREAD

**Issue by skiptheadventure** [aws-samples/amazon-dynamodb-labs#75]
This is a minor annoyance. I would suggest all console links target a new tab. It's just annoying to click the link and have to go back and open in a new tab.

**Comment by switch180** [comment]
Good idea. I cobbled together a js script that looks at the domain and sets the target to blank for console.aws.amazon.com links. This was done in the theme, in the hugo-learn.js file.

This change should make it to production shortly.

**Comment by switch180** [comment]
Pushed to prod. Resolving.
