### ISSUE TITLE
Migration from ACL to Bucket policy

### ISSUE THREAD

**Issue by renbrave** [aws-samples/amazon-dynamodb-labs#87]
Starting in April 2023, Amazon S3 will introduce two new default bucket security settings by automatically enabling S3 Block Public Access and disabling S3 access control lists (ACLs) for all new S3 buckets. The template used by the Event Engine solution needs to be updated.

https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-s3-automatically-enable-block-public-access-disable-access-control-lists-buckets-april-2023/

**Comment by switch180** [comment]
It is now fixed. The EE central account CFN stack will now create successfully.

Thank you for reporting the issue.
